# Generated by Django 5.2.8 on 2026-04-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ethical Meats', 'Ethical Meats'), ('Fresh Organics', 'Fresh Organics'), ('Pantry Essentials', 'Pantry Essentials'), ('Healthy Snacks', 'Healthy Snacks'), ('Baby Foods', 'Baby Foods'), ('Beverages', 'Beverages'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Dairy', 'Dairy'), ('Seafood', 'Seafood')], default='Dairy', max_length=100),
            preserve_default=False,
        ),
    ]
