# Generated by Django 6.0.6 on 2026-06-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='can_cancel',
            field=models.BooleanField(default=True),
        ),
    ]
