# Generated by Django 6.0.6 on 2026-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_order_can_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Razorpay', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.FloatField(default=0),
        ),
    ]
