# Generated by Django 5.2.8 on 2026-04-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('halal_certified', models.BooleanField(default=True)),
                ('ingredients', models.TextField()),
                ('source', models.CharField(max_length=200)),
            ],
        ),
    ]
